export const CREATE_THING = 'CREATE_THING';
export const FETCH_THINGS = 'FETCH_THINGS';
export const FETCH_THING = 'FETCH_THING';
export const UNSELECT_THING = 'UNSELECT_THING';
export const UPDATE_THING = 'UPDATE_THING';
export const DELETE_THING = 'DELETE_THING';
